### ISSUE TITLE
This Year's Data Mixed With Last

### ISSUE THREAD

**Issue by mdiasdev** [SwiftFest/ios-app#58]
It looks like as speakers are being announced, they are added to the database. However, the description of their talk is whatever was in the matching time slot from the previous year. (See Bob Martin).

**Expected**
When I tap on Bob Martin, I should see a description of his opening keynote

**Actual**
It appears Bob will be talking about his experience as the voice of Siri (Susan's keynote from last year)

**Comment by mdiasdev** [comment]
@GiorgioNatili this seems critical and likely a server change (this is happening in prod)

**Comment by ZevEisenberg** [comment]
Guessing it’s because talks and speakers have ids that need to match up on the server. It’s a pretty easy YAML change on the server repo; you just need to make sure that ids remain unique for a given type (speaker, talk, etc).

**Comment by mdiasdev** [comment]
I believe this has been fixed by updating the server content. Assigned to @GiorgioNatili to verify and close
